/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_springboottest_util_Tools */

#ifndef _Included_com_example_springboottest_util_Tools
#define _Included_com_example_springboottest_util_Tools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_springboottest_util_Tools
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_springboottest_util_Tools_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
